### ISSUE TITLE
プロジェクト構成図

### ISSUE THREAD

**Issue by faronan** [faronan/my-app#1]
# Backend
### ORM: Prisma
(他の選択肢)
- TypeORM

### GraphQLサーバー: Apollo Server
(他の選択肢)
- NestJSを採用して、自前のAPIサーバーを別途作成
- Hasuraサーバーを用意

### GraphQLスキーマ、型定義ファイルの自動生成: GraphQL Code Generator + Nexus

# Frontend
### フレームワーク: Next.js
(他の選択肢)
- CRA
- gatsby.js
- Nuxt.js(Vue)

### スタイリング: CSS Modules
(他の選択肢)
- CSS in JS

### 状態管理: React Hooks + Apollo Client
(他の選択肢)
- Recoil 

# 共通

#### テスト: Jest + React Testing Library
(他の選択肢)
- Enzyme

# インフラ

### Saas: Vercel
(他の選択肢)
- Netlify
- Firebase

### データベース: Cloud SQL for MySQL(GCP)
(他の選択肢)
- RDB(AWS)
- DynamoDB(AWS)

**Comment by faronan** [comment]
## TODO
- [ ] Prisma
- [ ] Apollo Server
- [ ] GraphQL Code Generator 
- [ ] Nexus
- [ ] Next.js
- [ ] Apollo Client
- [ ] ESLint
- [ ] Jest
- [ ] React Testing Library
- [ ] Vercel
- [ ] Cloud SQL for MySQL
